# =========================
# Application
# =========================
spring.application.name=sentinel
# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# =========================
# Liquibase
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info
# =========================
# Jwt
# =========================
jwt.secret=AX;vO]C-c2ol*=YbF#ywwfyNV4rElmk-r?YT$hGbbW2
jwt.access-token-expiration=900000
# =========================
# Invitation
# =========================
app.invitation-expiration=900000